# Generated by Django 5.2.13 on 2026-04-20 06:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название товара', max_length=255, verbose_name='Название товара')),
                ('description', models.TextField(help_text='Введите подробное описание товара', verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите цену товара', max_digits=10, verbose_name='Цена товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название заказа', max_length=255, verbose_name='Название заказа')),
                ('items', models.ManyToManyField(help_text='Выберите товары для заказа', related_name='orders', to='payments.item', verbose_name='Товары в заказе')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Укажите количество', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('item', models.ForeignKey(help_text='Укажите товары', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='payments.item', verbose_name='Товар')),
                ('order', models.ForeignKey(help_text='Укажите заказ', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='payments.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
    ]
