# Generated by Django 5.2.13 on 2026-04-20 07:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название скидки', max_length=255, verbose_name='Название скидки')),
                ('type', models.CharField(choices=[('percentage', 'Процент'), ('fixed', 'Фиксированная сумма')], help_text='Выберите тип скидки', max_length=20, verbose_name='Тип скидки')),
                ('value', models.DecimalField(decimal_places=2, help_text='Для процентов: число от 0 до 100, для фикс: сумма', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Значение скидки')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='payments.discount', verbose_name='Скидка'),
        ),
    ]
