# Generated by Django 5.2.13 on 2026-04-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_discount_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='stripe_coupon_id',
            field=models.CharField(blank=True, help_text='Заполняется автоматически', max_length=255, verbose_name='Stripe Coupon ID'),
        ),
    ]
