# Generated by Django 5.2.13 on 2026-04-20 08:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_discount_stripe_coupon_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название налога', max_length=255, verbose_name='Название налога')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Введите процент налога (число от 0 до 100)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Процент налога')),
                ('tax_rate_id', models.CharField(blank=True, help_text='Введите ID налоговой ставки из Stripe', max_length=255, verbose_name='Stripe Tax Rate ID')),
            ],
            options={
                'verbose_name': 'Налог',
                'verbose_name_plural': 'Налоги',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.ForeignKey(blank=True, help_text='Выберите скидку для товара', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='payments.discount', verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='stripe_coupon_id',
            field=models.CharField(blank=True, help_text='Введите ID купона из Stripe', max_length=255, verbose_name='Stripe Coupon ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, help_text='Выберите скидку для заказа', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='payments.discount', verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='item',
            name='tax',
            field=models.ForeignKey(blank=True, help_text='Выберите налог для товара', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='payments.tax', verbose_name='Налог'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.ForeignKey(blank=True, help_text='Выберите налог для заказа', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='payments.tax', verbose_name='Налог'),
        ),
    ]
