# Generated by Django 5.2.13 on 2026-04-20 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_tax_item_discount_alter_discount_stripe_coupon_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
    ]
