# Generated by Django 5.2.13 on 2026-04-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_item_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tax',
        ),
        migrations.AddField(
            model_name='item',
            name='taxes',
            field=models.ManyToManyField(blank=True, help_text='Выберите налоги для товара', related_name='items', to='payments.tax', verbose_name='Налоги'),
        ),
    ]
