# Generated by Django 5.2.13 on 2026-04-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_item_tax_item_taxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('USD', 'Доллар США'), ('EUR', 'Евро'), ('RUB', 'Российский рубль')], default='RUB', help_text='Выберите валюту (например, USD)', max_length=3, verbose_name='Валюта'),
            preserve_default=False,
        ),
    ]
