# Generated by Django 5.2.13 on 2026-04-21 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_item_currency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'item')},
        ),
    ]
